config/routes.rb
Myapp::Application.routes.draw do
  get "welcome/index"

  resources :posts
  resources :tracker
  
  root 'welcome#index'

  get 'tracker/update/:name', to: 'tracker#update'
  get 'tracker/track/:name(/:skill)(/:time)', to: 'tracker#track'

  get 'tracker/pidtoname/:pid', to: 'tracker#pidtoname'
  get 'tracker/nametopid/:name', to: 'tracker#nametopid'
  get 'tracker/formatname/:name', to: 'tracker#formatname'

  

end

app/models/data_point.rb
class DataPoint < ActiveRecord::Base
end

app/models/name_mappings.rb
class NameMappings < ActiveRecord::Base
  before_create :fix_name

  def fix_name
    self.name = NameMappings.get_player_name self.name
  end

  def self.get_player_name unsafe_name
    return unsafe_name.gsub(/[^a-zA-Z0-9_\- ]/, "").gsub(/[\-_]/, " ").downcase.strip.gsub(' ','_')
  end

  def self.find_by_name player_name 
    player_name = get_player_name player_name 
    find_by(:name => player_name)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence:true, 
    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @title = "New Post"
  end

	def index
    @posts = Post.all
    @title = "Message Board"
	end

  def show
    @post = Post.find(params[:id])
    @title = "Show Post"
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(params[:post].permit(:title, :text)))
      redirect_to @post
    else
      render 'edit'
    end
    @title = "Edit Post"
  end

  def edit
    @post = Post.find(params[:id])
    @title = "Edit Post"
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text))
    if @post.save
      redirect_to @post
    else 
      render 'new'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/tracker_controller.rb
class TrackerController < ApplicationController
  include TrackerHelper
  require 'open-uri'

  def index
    @namemappings = NameMappings.all
    @datapoints = DataPoint.all
  end

  def update
    @title = "Update " << params[:name]

    begin
      get_current_stats params[:name]

      @namemap = NameMappings.find_by_name(params[:name])
      if(@namemap == nil)
        @namemap = NameMappings.new(params.permit(:name))
        @namemap.save
      end

      @dp = DataPoint.new(:pid => @namemap.id, :time => Time.now.to_i, :xp => @xphex, :rank => @rankhex)
      @dp.save
    rescue OpenURI::HTTPError
      params[:name] = nil
    end
  end

  def track
    @time = (params[:time] == nil ? 86400 : params[:time].to_i)
    @skill = get_skill(params[:skill] == nil ? 0 : params[:skill].to_i)

    @namemap = NameMappings.find_by_name(params[:name])
    if(@namemap != nil)
      @datapoints = DataPoint.where(pid: @namemap.id).where(updated_at: (Time.now - @time)..Time.now)
    end
  end

  def nametopid
    @namemap = NameMappings.find_by_name(params[:name])
  end

  def pidtoname
    @namemap = NameMappings.find_by(params.permit(:pid))
  end

  def formatname
    @name = get_player_name params[:name]
    @test = get_skill_name(1)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tracker_helper.rb
module TrackerHelper
  def cap_words str
    str.split(' ').map {|w| w.capitalize }.join(' ')
  end

  def get_skill_name i
    return @@skills[i]
  end

  def get_skill unsafe_id
    skill = unsafe_id.to_i
    if(-1 < skill && skill < 24)
      return skill
    else
      return 0
    end
  end

  def pluralize( count, unit )
    return count.to_s << " " << unit << (count == 1 ? "" : "s")
  end

  def items_in_series( item_array )
    ret = ""
    item_array.each_with_index do |item, i|
      ret << item << (item_array.length - 1 == i ? "" : ", ") << (item_array.length - 2 == i ? "and " : "")
    end
    return ret
  end

  def get_current_stats player_name
      contents = open('http://services.runescape.com/m=hiscore_oldschool/index_lite.ws?player=' << NameMappings.get_player_name(player_name)) { |io| io.read }
      @xp = Array.new(24)
      @ranks = Array.new(24)
      skillarr = contents.split /\r?\n/

      @xphex = ""
      @rankhex = ""

      0.upto 23 do |i|
        skillarr[i] = skillarr[i].split(',')
        @ranks[i] = skillarr[i][0].to_i
        @xp[i] = skillarr[i][2].to_i
        @xphex << @xp[i].to_s(16).rjust(8, '0')
        @rankhex << @ranks[i].to_s(16).rjust(8, '0')
      end
  end


  @@skills = [
    "Overall","Attack","Defence","Strength","Hitpoints",
    "Ranged","Prayer","Magic","Cooking","Woodcutting",
    "Fletching","Fishing","Firemaking","Crafting","Smithing",
    "Mining","Herblore","Agility","Thieving","Slayer",
    "Farming","Runecrafting","Hunter","Construction"
  ]

  @@time_units = [
      [31536000, 2678400, 604800, 86400, 3600, 60, 1],
      %w(y M w d h m s),
      %w(year month week day hour minute second)
    ]

  @@time_seconds = 0
  @@time_symbols = 1
  @@time_names = 2

  def time_to_short_string( time )
    if(time == 0)
      return "0s"
    end
    
    ret = ""
    for i in (3...7)
      count = time / @@time_units[@@time_seconds][i]
      if(count > 0)
        ret << count.to_s << @@time_units[@@time_symbols][i]
      end 
      time %= @@time_units[@@time_seconds][i]
    end
    return ret
  end

  def time_to_string( time )
    if(time == 0)
      return "0s"
    end
    
    time_counts = Array.new(4)
    non_zeo_count = 0
    
    for i in (3...7)
      count = time / @@time_units[@@time_seconds][i]
      if(count > 0)
        non_zeo_count += 1
        time_counts[i-3] = pluralize( count, @@time_units[@@time_names][i] )
      end
      time %=  @@time_units[@@time_seconds][i]
    end
    time_counts.compact!
    return items_in_series( time_counts )
  end

  def short_string_to_time( short_time_string )
    ret = 0
    current_number = ""
    for i in (0...short_time_string.length)
      if(is_numeric_char(short_time_string[i]))
        current_number << short_time_string[i]
      else
        for k in (0...7)
          if(short_time_string[i] == @@time_units[@@time_symbols][k])
            ret += @@time_units[@@time_seconds][k] * current_number.to_i
            current_number = ""
          end
        end
      end
    end
    ret += current_number.to_i
    return ret
  end

  def get_icon_url( skill )
      return "/ico/" + (skill).to_s + ".gif"
  end

  def track_path( name, skill, time )
    return ('/tracker/track/' << name << '/' << skill.to_s << '/' << time.to_s)
  end

  def display_name player_name
    return cap_words player_name.gsub("_"," ")
  end

  def color_number i
    if i > 0
      return "<span class='positive'>+" << i.to_s << "</span>"
    elsif i < 0
      return "<span class='negative'>" << i.to_s << "</span>"
    else
      return "0"
    end

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= (@title != nil ? @title + " - " : "") %> Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <% javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for :post, url: post_path(@post.id) ,
method: :patch do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= link_to 'New post', new_post_path %>

<h1>Listing posts</h1>
  
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
     
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<%= link_to 'Back', posts_path %>

<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<div id="errorExplanation">
			<h2>
				<%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
			</h2>
	    <ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
 
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>
 
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/show.html.erb
<%= link_to 'Back', posts_path %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

app/views/tracker/formatname.html.erb
<%= @name %><br/>
<%= @test %>

app/views/tracker/index.html.erb
<h3>Displaying all name mappings: </h3>
<% @namemappings.each do |item| %>
<%= item.id %> = <%= link_to item.name, track_path(item.name, 0, 86400) %><br/>
<% end %>

<h3>Displaying all data points: </h3>
<% @datapoints.each do |item| %>
PID <%= item.pid %><br/>
Time <%= time_to_string(Time.now.to_i - item.created_at.to_i) %> ago<br/>
XP <%= item.xp %><br/>
Rank <%= item.rank %><br/><br/>
<% end %>

app/views/tracker/namemappings.html.erb
<% @namemappings.each do |item| %>

<%= item.id %> = <%= item.name %><br/>

<% end %>

app/views/tracker/nametopid.html.erb
<%= @namemap.id %>

app/views/tracker/pidtoname.html.erb
<%= @namemap.name %>

app/views/tracker/track.html.erb
<% if @namemap.nil? %>
The name <%= params[:name] %> is not in the database.<br/>
<%= link_to 'Update', '/tracker/update/' << params[:name] %>
<% else %>
<% if @datapoints.empty? %>
There is no data for this player within this time period.<br/>
<%= link_to 'Update', '/tracker/update/' << @namemap.name %>
<% else %>
Tracking <%= @namemap.name %> - <%= link_to 'Update', '/tracker/update/' << @namemap.name %><br/>
Most recent data point: <%= time_to_string(Time.now.to_i-@datapoints[-1].created_at.to_i) %> ago<br/>
Earliest data point within this time period: <%= time_to_string(Time.now.to_i-@datapoints[0].created_at.to_i) %> ago<br/>
<%= @time==86400 ? 'Day' : (link_to 'Day', '/tracker/track/' << @namemap.name << '/' << @skill.to_s << '/86400') %>
<%= @time==604800 ? 'Week' : (link_to 'Week', '/tracker/track/' << @namemap.name << '/' << @skill.to_s << '/604800') %>
<%= @time==2678400 ? 'Month' : (link_to 'Month', '/tracker/track/' << @namemap.name << '/' << @skill.to_s << '/2678400') %>
<h3>
	Tracking <%= display_name @namemap.name %> within the last <%= time_to_string(@time) %>:
</h3>
<table>
	<tr>
		<td>
			Skill
		</td>
		<td>
			XP
		</td>
		<td>
			Rank
		</td>
	</tr>
<% 0.upto 23 do |i| %>
	<tr>
		<td>
			<%= image_tag get_icon_url i  %>
			<%= i == @skill ? '>' << get_skill_name(i) : link_to(get_skill_name(i), track_path(@namemap.name, i, @time)) %>
		</td>
		<td>
			<%=raw color_number(@datapoints[-1].xp[i*8,8].hex - @datapoints[0].xp[i*8,8].hex) %>
		</td>
		<td>
			<%=raw color_number(@datapoints[0].rank[i*8,8].hex - @datapoints[-1].rank[i*8,8].hex) %>
		</td>
	</tr>
<% end %>
</table>
<br/><%= get_skill_name @skill %> graphs:<br/><br/>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
google.load('visualization', '1', {packages:['corechart']});
google.setOnLoadCallback(drawChart);
function drawChart() {
	var xpdata = new google.visualization.DataTable();
	xpdata.addColumn('date', 'Date');
	xpdata.addColumn('number', 'XP');
	xpdata.addColumn({type:'string', role:'tooltip', p: { html: true }});
	 
	var rankdata = new google.visualization.DataTable();
	rankdata.addColumn('date', 'Date');
	rankdata.addColumn('number', 'Rank');
	rankdata.addColumn({type:'string', role:'tooltip', p: { html: true }});
	
	var lvldata = new google.visualization.DataTable();
	lvldata.addColumn('date', 'Date');
	lvldata.addColumn('number', 'Level');
	lvldata.addColumn({type:'string', role:'tooltip', p: { html: true }});
	function ISODateString(d) {
	   function pad(n) {
			return n < 10 ? '0' + n : n;
		
		}

		return pad(d.getHours()) + ':'
			+ pad(d.getMinutes()) + ':'
			+ pad(d.getSeconds()) + ' '
			+ pad(d.getDate()) + "/"
			+ pad(d.getMonth() + 1) + "/"
			+ pad(d.getFullYear());
	}

	function makeRows(timestamp, xp, lvl, rank) {
		var d    = new Date(timestamp),
		   dstr = "<span class='tooltip'><strong>"
			+ ISODateString(d) + "</strong><br>",
		   dend = "</span>";

		var xprow   = [d, xp,   dstr + "XP : "    + xp   + dend],
			lvlrow  = [d, lvl,  dstr + "Level : " + lvl  + dend],
			rankrow = [d, rank, dstr + "Rank : "  + rank + dend];

		if (xp   != null) xpdata.addRow(xprow);
		if (lvl  != null) lvldata.addRow(lvlrow);
		if (rank != null) rankdata.addRow(rankrow);
	}

	<% @datapoints.each do |item| %>
	makeRows(<%= item.created_at.to_i %>000,<%= item.xp[@skill*8,8].hex %>,0,<%= item.rank[@skill*8,8].hex %>);
	<% end %>

	var xpoptions = {
	  title: '<%= get_skill_name @skill %> XP (<%= time_to_string @time %>)',
	  backgroundColor: 'ededed',
	  tooltip: { isHtml: true },
	  chartArea: {
			left: 90,
			height: '75%',
			width: '75%'
		},
		legend: { position: 'none' }
	};
	var xpchart = new google.visualization.LineChart(document.getElementById('xpgraph'));
	xpchart.draw(xpdata, xpoptions);
	
	var lvloptions = {
		title: '<%= get_skill_name @skill %> Levels (<%= time_to_string @time %>)',
		backgroundColor: 'ededed',
		tooltip: { isHtml: true },
		chartArea: {
			left: 90,
			height: '75%',
			width: '75%'
		},
		legend: { position: 'none' }
	};
	var lvlchart = new google.visualization.LineChart(document.getElementById('lvlgraph'));
	lvlchart.draw(lvldata, lvloptions);
	
	var rankoptions = {
		vAxis: {direction: -1},
		title: '<%= get_skill_name @skill %> Ranks (<%= time_to_string @time %>)',
		backgroundColor: 'ededed',
		tooltip: { isHtml: true },
		chartArea: {
			left: 90,
			height: '75%',
			width: '75%'
		},
		legend: { position: 'none' }
	};
	var rankchart = new google.visualization.LineChart(document.getElementById('rankgraph'));
	rankchart.draw(rankdata,rankoptions);
}
</script>
<div id='xpgraph' style='width: 675px; height: 375px;'></div>
<div id='rankgraph' style='width: 675px; height: 375px;'></div>
<div id='lvlgraph' style='width: 675px; height: 375px;'></div>
<% end %>
<% end %>

app/views/tracker/update.html.erb
<% if(@namemap == nil) %>
	This player is not on the Old School RuneScape hiscores.
<% else %>
	<%= link_to 'Track', track_path(@namemap.name, 0, 86400) %><br/>
	Time <%= Time.now.to_i %><br/>
	Name <%= @namemap.name %><br/>
	PID <%= @namemap.id %><br/>
	namemap <%= @namemap.inspect %>
	<table>
		<tr>
			<td>Skill Name</td>
			<td>XP</td>
			<td>Rank</td>
		</tr>
	<% 0.upto 23 do |i| %>
		<tr>
			<td>
				<%= get_skill_name i %>
			</td>
			<td>
				<%= @xp[i] %>
			</td>
			<td>
				<%= @ranks[i] %>
			</td>
		</tr>
	<% end %>
	</table>
<% end %>

app/views/welcome/index.html.slim
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<div class="container-narrow">
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  </button>
      <a class="brand">07 Xp Tracker</a>
      <div class="nav-collapse collapse">
      <ul class="nav">
      <li class="active"><a href="/tracker">Tracker</a></li>
      <li><a href="/posts">Announcements/Message Board</a></li>
      </ul>
</div>
</div>
</div>
</div>
<div class="container">
<div class="container-narrow">
<h1>Hello!</h1>
</div>
</div>